# Generated by Django 5.2.15 on 2026-06-29 14:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nomba_request_id", models.CharField(max_length=200, unique=True)),
                ("amount_naira", models.DecimalField(decimal_places=2, max_digits=14)),
                ("amount_kobo", models.BigIntegerField()),
                ("event_type", models.CharField(max_length=50)),
                (
                    "merchant_tx_ref",
                    models.CharField(blank=True, max_length=200, unique=True),
                ),
                ("sender_name", models.CharField(blank=True, max_length=200)),
                ("sender_account", models.CharField(blank=True, max_length=20)),
                ("raw_payload", models.JSONField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="contributions.contributor",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["contributor"], name="payments_pa_contrib_7a746b_idx"
                    ),
                    models.Index(
                        fields=["processed_at"], name="payments_pa_process_0233b1_idx"
                    ),
                ],
            },
        ),
    ]
