# Generated by Django 5.2.15 on 2026-06-29 14:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pots", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contributor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("is_anonymous", models.BooleanField(default=False)),
                ("wants_group_notifications", models.BooleanField(default=False)),
                (
                    "virtual_account_id",
                    models.CharField(blank=True, max_length=100, unique=True),
                ),
                ("virtual_account_number", models.CharField(blank=True, max_length=10)),
                (
                    "virtual_account_bank_name",
                    models.CharField(blank=True, max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "pot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contributors",
                        to="pots.pot",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contributions_as_contributor",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "intended_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("partial", "Partial"),
                            ("overpaid", "Overpaid"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contribution",
                        to="contributions.contributor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pledge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pledged_amount",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "total_paid",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("is_complete", models.BooleanField(default=False)),
                ("last_payment_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributor",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pledge",
                        to="contributions.contributor",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="contributor",
            index=models.Index(
                fields=["virtual_account_id"], name="contributio_virtual_3f0819_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="contributor",
            unique_together={("pot", "email")},
        ),
        migrations.AddIndex(
            model_name="pledge",
            index=models.Index(
                fields=["is_complete", "last_payment_at"],
                name="contributio_is_comp_0b7400_idx",
            ),
        ),
    ]
