# Generated by Django 5.2.15 on 2026-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contributions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contributor",
            name="virtual_account_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
